### ISSUE TITLE
etherpad-generated author text backgrounds look bad with dark background

### ISSUE THREAD

**Issue by ghost** [ether/ep_themes#3]
Example: 

![badetherpad](https://cloud.githubusercontent.com/assets/5308179/4820009/eb557f1a-5f0d-11e4-9009-98226de6529a.png)

This is most likely an issue with the default luminosity of the generated author bgcolors (https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L253). (specifically `fadeColor()`?)

Will experiment and check back later.

**Comment by JohnMcLear** [comment]
@talexand how did your experiments go?

**Comment by JohnMcLear** [comment]
Should be fixed now :)
