### ISSUE TITLE
CSS based approach

### ISSUE THREAD

**Issue by LaKing** [ether/ep_themes#4]
In codepad I implemented themes with the approach of extracting all CSS and then setting custom CSS files. We should go that path, with ep_themes.

the only thing prevented me until now was that the theme selected was encoded in cookies, and in my plugin I had to use the data as it is, without encoding it within the etherpad system.

So I either need a method explained how to read-write theme selection in a plugin, or we could use the theme selection stored in a basic cookie.

@JohnMcLear, what do you think?

**Comment by JohnMcLear** [comment]
+1 :)

________________________________

**Comment by JohnMcLear** [comment]
Done :)
